## Загрузка библиотек и данных

In [1]:
import pandas as pd
import zipfile
import os
import time
import re
import nltk
import numpy as np

In [2]:
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt')
from nltk.tokenize import word_tokenize # плохо обработались слова
from nltk.tokenize import RegexpTokenizer
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from collections import Counter
from sklearn.feature_extraction.text import CountVectorizer,  TfidfTransformer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


In [3]:
!pip install pysrt
import pysrt

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.4/104.4 kB 1.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for pysrt: filename=pysrt-1.1.2-py3-none-any.whl size=13443 sha256=e5d4b1253fbd8340466b0738ec54515bafbb36dd9b76ead84d7dd56a198963a2
  Stored in directory: /root/.cache/pip/wheels/30/7f/e8/55de9a9b07302d9e7fe47c27910e3bea0c48536153e74bd7e6
Successfully built pysrt


In [4]:
from google.colab import drive
from PIL import Image

In [5]:
!pip install pypdf
from pypdf import PdfReader

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 269.8/269.8 kB 3.1 MB/s eta 0:00:00


In [6]:
drive.mount('/content/drive')

Mounted at /content/drive


### Создание дф

In [7]:
# чтобы разгрузить код я буду путь к файлам сохранять в эту переменную
PATH = None

In [8]:
# создаем датафрейм
PATH = '/content/drive/MyDrive/Masterskaya_2/English_scores.zip (Unzipped Files)/movies_labels.xlsx'
data = pd.read_excel(PATH)
data.head()

id                             Movie   Level
0   0         10_Cloverfield_lane(2016)      B1
1   1  10_things_I_hate_about_you(1999)      B1
2   2              A_knights_tale(2001)      B2
3   3              A_star_is_born(2018)      B2
4   4                     Aladdin(1992)  A2/A2+

In [9]:
# приведем названия столбцов к каноническому виду
data.columns = ['id', 'movie', 'level']
data.head()

id                             movie   level
0   0         10_Cloverfield_lane(2016)      B1
1   1  10_things_I_hate_about_you(1999)      B1
2   2              A_knights_tale(2001)      B2
3   3              A_star_is_born(2018)      B2
4   4                     Aladdin(1992)  A2/A2+

In [10]:
data.shape[0]

241

In [11]:
# читаем файл с субтитрами
PATH = '/content/drive/MyDrive/Masterskaya_2/English_scores.zip (Unzipped Files)/Subtitles_all/Subtitles/10_Cloverfield_lane(2016).srt'
subs = pysrt.open(PATH)


In [12]:
# я посмотрела как будут выглядеть субтитры
subtitle_texts = [subtitle.text for subtitle in subs]
subtitle_texts[:10]

['<font color="#ffff80"><b>Fixed & Synced by bozxphd. Enjoy The Flick</b></font>',
 '(CLANGING)',
 '(DRAWER CLOSES)',
 '(INAUDIBLE)',
 '(CELL PHONE RINGING)',
 "BEN ON PHONE: <i>Michelle,<br/>please don't hang up.</i>",
 "<i>Just talk to me, okay?<br/>I can't believe you just left.</i>",
 '<i>Michelle.</i>',
 '<i>Come back.</i>',
 '<i>Please say something.</i>']

Для того, чтобы получить субтитры в удобноваримом формате, мы пройдемся циклом по всему содержимому папки Subtitles, которая содержит папки с названиями фильмов. Для этого используем модуль os, который позволяет работать с файлами и директориями.

In [13]:
PATH = '/content/drive/MyDrive/Masterskaya_2/English_scores.zip (Unzipped Files)/Subtitles_all/'

In [14]:
PATH = '/content/drive/MyDrive/Masterskaya_2/English_scores.zip (Unzipped Files)/Subtitles_all/'

def get_subs():
    subtitles = []
    movie = []

    # Получаем все папки и файлы в указанной папке
    film_list = os.listdir(PATH)

    for folder in film_list:
        for film in os.listdir(os.path.join(PATH, folder)):
            # достаем названия
            last_dot = film.rfind('.')
            movie.append(film[:last_dot])

            # субтитры
            # собираем название путь
            file_to_read = os.path.join(PATH, folder, film)  # Исправленный путь к файлу
            # расшифровываем
            try:
                encoded_film = pysrt.open(file_to_read, encoding='iso-8859-1')
            except:
                encoded_film = pysrt.open(file_to_read, encoding='UTF-8')

            # трансформируем в текст
            subs_text = [film.text for film in encoded_film]
            subtitles.append(subs_text)

    return pd.DataFrame({'subs': subtitles, 'movie': movie})


Обращаем внимание, что имеются строки в которых точка используется как разделитель, это важно, так как нам нужно сохранить названия фильмов без расширения .srt

---

Делить будем так:
- находим индекс где стоит **последняя** точка
- добавляем строку до этого индекса

In [15]:
subs_df = get_subs()
subs_df.head()

subs  \
0  [- ( walkie-talkie squawks )\n- Rick: Morgan,,...   
1  [- ( people yelling )\n- ( radio chatter ), He...   
2  [( birds chirping ), - What?\n- Nothing., It's...   
3  [( thunder rumbling ), Merle:\nThat's right. Y...   
4  [- ( birds chirping )\n- ( bugs chittering ), ...   

                                               movie  
0           The Walking Dead-S01E05-Wildfire.English  
1              The Walking Dead-S01E06-TS-19.English  
2              The Walking Dead-S01E04-Vatos.English  
3  The Walking Dead-S01E03-Tell It To The Frogs.E...  
4               The Walking Dead-S01E02-Guts.English

In [16]:
subs_df.shape[0]

278

Теперь можно обработать названия фильмов, чтобы добавить субтитры к фильмам.
Обрабатывать буду следующими шагами:
- все слова к строчному регистру
- в качестве разделителя только знак нижнего подчеркивания "_"
- удалю все пробелы, знаки между словами, оставлю только цифры.

In [17]:
data.head()

id                             movie   level
0   0         10_Cloverfield_lane(2016)      B1
1   1  10_things_I_hate_about_you(1999)      B1
2   2              A_knights_tale(2001)      B2
3   3              A_star_is_born(2018)      B2
4   4                     Aladdin(1992)  A2/A2+

In [18]:
def transform_values(df):
    # заменяем пробелы на underscore
    df = df.applymap(lambda x: x.replace(' ', '_') if isinstance(x, str) else x)

    # заменяем дефис на underscore
    df = df.applymap(lambda x: x.replace('-', '_') if isinstance(x, str) else x)

    # добавляем underscore между словом и цислом
    df = df.applymap(lambda x: '_'.join(part for part in x.split() if not part.isdigit()) if isinstance(x, str) else x)
    # приводим к строчному регистру
    df = df.applymap(lambda x: x.lower() if isinstance(x, str) else x)

    return df


In [19]:
# почистим названия фильмов в дата
data = transform_values(data)
data.head()

id                             movie   level
0   0         10_cloverfield_lane(2016)      b1
1   1  10_things_i_hate_about_you(1999)      b1
2   2              a_knights_tale(2001)      b2
3   3              a_star_is_born(2018)      b2
4   4                     aladdin(1992)  a2/a2+

In [20]:
subs_df = transform_values(subs_df)
subs_df.head()

subs  \
0  [- ( walkie-talkie squawks )\n- Rick: Morgan,,...   
1  [- ( people yelling )\n- ( radio chatter ), He...   
2  [( birds chirping ), - What?\n- Nothing., It's...   
3  [( thunder rumbling ), Merle:\nThat's right. Y...   
4  [- ( birds chirping )\n- ( bugs chittering ), ...   

                                               movie  
0           the_walking_dead_s01e05_wildfire.english  
1              the_walking_dead_s01e06_ts_19.english  
2              the_walking_dead_s01e04_vatos.english  
3  the_walking_dead_s01e03_tell_it_to_the_frogs.e...  
4               the_walking_dead_s01e02_guts.english

In [21]:
subs_df['movie'] = transform_values(subs_df[['movie']])
subs_df['movie'].head()

0             the_walking_dead_s01e05_wildfire.english
1                the_walking_dead_s01e06_ts_19.english
2                the_walking_dead_s01e04_vatos.english
3    the_walking_dead_s01e03_tell_it_to_the_frogs.e...
4                 the_walking_dead_s01e02_guts.english
Name: movie, dtype: object

In [22]:
subs_df.head()

subs  \
0  [- ( walkie-talkie squawks )\n- Rick: Morgan,,...   
1  [- ( people yelling )\n- ( radio chatter ), He...   
2  [( birds chirping ), - What?\n- Nothing., It's...   
3  [( thunder rumbling ), Merle:\nThat's right. Y...   
4  [- ( birds chirping )\n- ( bugs chittering ), ...   

                                               movie  
0           the_walking_dead_s01e05_wildfire.english  
1              the_walking_dead_s01e06_ts_19.english  
2              the_walking_dead_s01e04_vatos.english  
3  the_walking_dead_s01e03_tell_it_to_the_frogs.e...  
4               the_walking_dead_s01e02_guts.english

Сделаю тип объединения outer так как могут удалиться дубликаты, а я хочу сохранить все наблюдения и отдельно обработать дубликаты чтобы избежать ошибок.

In [23]:
data = pd.merge (subs_df,data,
                 on = 'movie',
                 how = 'outer',
                 indicator = True)
data.head()

subs  \
0  [- ( walkie-talkie squawks )\n- Rick: Morgan,,...   
1  [- ( people yelling )\n- ( radio chatter ), He...   
2  [( birds chirping ), - What?\n- Nothing., It's...   
3  [( thunder rumbling ), Merle:\nThat's right. Y...   
4  [- ( birds chirping )\n- ( bugs chittering ), ...   

                                               movie     id level _merge  
0           the_walking_dead_s01e05_wildfire.english  116.0    a2   both  
1              the_walking_dead_s01e06_ts_19.english  117.0    a2   both  
2              the_walking_dead_s01e04_vatos.english  115.0    a2   both  
3  the_walking_dead_s01e03_tell_it_to_the_frogs.e...  114.0    a2   both  
4               the_walking_dead_s01e02_guts.english  113.0    a2   both

In [24]:
data['_merge'].value_counts()

both          233
left_only      49
right_only      8
Name: _merge, dtype: int64

видим что у нас остались 49 фильмов только из датафрейма subs_df и 8 только из data.
очевидно, что для 49 фильмов у нас нет разметки по уровню и для 8 нет субтитров.

In [25]:
data.loc[(data['_merge']=='left_only') | (data['_merge']=='right_only')]

subs  \
38   [On the clothes we wear,, the people who make ...   
39   [Yes., Ah, there you are. Come in., I'm practi...   
40   [[woman speaks French] Your Majesty., [planes ...   
41   [[music plays]\n<i>...and then I swing you aro...   
42   [[child]<i> Gina! Gina! Ella!</i>, -Gina! Cari...   
43   [- Fuel on.\n- Fuel on., Chocks are in positio...   
44   [[fanfare plays], [man] <i>More than half a mi...   
45   [[coughing], [coughing continues], [spits], [e...   
46   [<i>...and then I swing you around there.</i>,...   
47   [<i>♪ If your sweetheart ♪</i>, <i>♪ Sen...   
48   [Your Majesty., So, it is always the Sovereign...   
49   [[brass band plays in distance], [door opens],...   
50   [<i> Gina! Gina! Ella!</i>, -Gina! Carina! Ell...   
51   [-Ask my daughters to come and see me.\n-Yes, ...   
52   [This way, madam., At the end of the bar., -He...   
53   ["My husband and I are deeply touched\nby our ...   
54   [[doors creak open], -Fuel on.\n-[Philip] Fuel...   
55   [Dear Aunt, forgive the intrusion., I come dir...   
56   [-Ask my daughters to come and see me.\n-Yes, ...   
57   [I am delighted to be here in Cairo, to meet w...   
58   [In seeking his British\nnationalization, His ...   
59   [<i>More than half a million people</i>\n<i>pa...   
60   ["My husband and I are deeply touched\nby our ...   
61   [Your Majesty., So, it is\nalways the Sovereig...   
62   [<i>For the sixth time</i>\n<i>in the history ...   
80   [Line drive to right field..., Solemnly swear ...   
98   [Oh., - Oh, yeah.\n- Okay., - Hey.\n- Hey., - ...   
99   [You're Chloe's mother., You... you said she w...   
100  [Hey., Hey., Wouldn't a chainsaw be easier?, Y...   
101  [♪ I woke up and wished that I was dead ♪,...   
102  [Are you sure I can't convince you to stay?, N...   
103  [Come on., - You can put him on the table.\n- ...   
104  [Two IVs in place in antecubital fossae., - An...   
105  [- There you go.\n- Thank the Lord., Home swee...   
106  [So, how long have you known?, I've suspected ...   
107  [Get in the truck., I got a better idea., Why ...   
108  [(PEOPLE VOCALIZING\nRHYTHMICALLY), (MORE VOIC...   
109  [The hills are alive, With the sound of music,...   
110  [Illumination!, Yeah! Illumination!, Whoo!\n(W...   
129  [Here's something\nthat should hurt your brain...   
134  [[presenter]\n<i>She spent 20 years studying c...   
219  [I should've known that you would\nbe here, Pr...   
221  [{\i1}Movietown{\i0}\n{\i1}News presents Spotl...   
238  [[Music], no one's complained, [Music], there'...   
239  [[Music], so, [Music], wow, [Music], hello hel...   
240  [what hi good to meet you all nice to, meet yo...   
241  [[Music], [Music], okay one picture in my hist...   
242  [[Music], [Music], so, [Music], [Music], [Musi...   
243  [[Music], so, [Music], um, [Music], [Music], s...   
282                                                NaN   
283                                                NaN   
284                                                NaN   
285                                                NaN   
286                                                NaN   
287                                                NaN   
288                                                NaN   
289                                                NaN   

                                                 movie     id   level  \
38     the.true.cost.2015.bluray.720p.700mb.ganool.com    NaN     NaN   
39            crown,_the_s01e05___smoke_and_mirrors.en    NaN     NaN   
40    crown,_the_s01e07___scientia_potentia_est.en.sdh    NaN     NaN   
41                 crown,_the_s01e10___gloriana.en.sdh    NaN     NaN   
42                  crown,_the_s01e03___windsor.en.sdh    NaN     NaN   
43                   crown,_the_s01e04___act_of_god.en    NaN     NaN   
44                crown,_the_s01e06___gelignite.en.sdh    NaN     NaN   
45         crown,_the_s01e01___wolferton_splash.en.sdh    NaN     NaN   
46                     crown


reader = PdfReader('/content/drive/MyDrive/Masterskaya_2/Oxford_CEFR_level/American_Oxford_3000_by_CEFR_level.pdf')
number_of_pages = len(reader.pages)
page = reader.pages[0]
text = page.extract_text

In [26]:
os.listdir('/content/drive/MyDrive/Masterskaya_2/Oxford_CEFR_level')

['The_Oxford_5000_by_CEFR_level.pdf',
 'The_Oxford_3000_by_CEFR_level.pdf',
 'American_Oxford_5000_by_CEFR_level.pdf',
 'American_Oxford_3000_by_CEFR_level.pdf']

нужно либо маску разделитель уровней прописать либо предварительно вручную разграничить по уровням, потому что пока непонятно как работать с этим форматом text

## Предобработка и анализ

In [27]:
data.dtypes

subs        object
movie       object
id         float64
level       object
_merge    category
dtype: object

## Пропуски

На данном этапе заполню пропуски заглушкой 'no_subs', все пропуски возникли по понятной мне причине и их немного. Оставлю я их для того чтобы потом заполнить на стадии обогащения датасеты. А сейчас мне нужно просто получить baseline модель и такие данные сгодятся

In [28]:
plug = 'no_info'

In [29]:
data = data.fillna(plug)
data.isna().sum()

subs      0
movie     0
id        0
level     0
_merge    0
dtype: int64

## Дупликаты

In [30]:
data['movie'].duplicated().sum()

4

In [31]:
duplicates = data[data['movie'].duplicated()]
duplicates

subs                 movie  \
151  [Advertise your product or brand here<br/>cont...      inside_out(2015)   
175  [EMT 1:\nAll right, people,\nlet's move! Let's...          powder(1995)   
185  [[CROWD CHEERING IN DISTANCE], LElGH ANNE: The...  the_blind_side(2009)   
228  [<font color="#D900D9">(AIRPLANE APPROACHES)</...    the_terminal(2004)   

       id       level _merge  
151  44.0          b1   both  
175  68.0          b1   both  
185  84.0          b1   both  
228  99.0  a2/a2+,_b1   both

Мы увидели только ошибочные дупликаты, удалять их не будем.

### Обработка субтитров

In [32]:
data.head()

subs  \
0  [- ( walkie-talkie squawks )\n- Rick: Morgan,,...   
1  [- ( people yelling )\n- ( radio chatter ), He...   
2  [( birds chirping ), - What?\n- Nothing., It's...   
3  [( thunder rumbling ), Merle:\nThat's right. Y...   
4  [- ( birds chirping )\n- ( bugs chittering ), ...   

                                               movie     id level _merge  
0           the_walking_dead_s01e05_wildfire.english  116.0    a2   both  
1              the_walking_dead_s01e06_ts_19.english  117.0    a2   both  
2              the_walking_dead_s01e04_vatos.english  115.0    a2   both  
3  the_walking_dead_s01e03_tell_it_to_the_frogs.e...  114.0    a2   both  
4               the_walking_dead_s01e02_guts.english  113.0    a2   both

- перевести значения в признаке subs в формат str
- нужно создать дополнительный столбец, чтобы превратить субтитры в кортеж из слов
- удалить символы кроме пробела и '', так как по длине фраз так же можно сделать предположение о сложности текста
- привести слова к первоначальной форме (ед число, настоящее время)/ лемматизация
- привести все слова к нижнему регистру
- удалить стоп-слова


In [32]:
# пробуем заменить символы
data['subs'] = data['subs'].replace('\n', '\t', regex=True)
data['subs'][0][:5]

['- ( walkie-talkie squawks )\n- Rick: Morgan,',
 "I don't know if you're out there.",
 "I don't know\nif you can hear me.",
 "Maybe you're listening right now.",
 'I hope so.']

Видим, что остались символы \n без пробела, но на данном этапе не получилось их убрать не используя регулярные выражения.


---

data['sub'] содержит субтитры, которые представлены в формате список списков.
Каждый список (фильм) содержит список предложений, каждое предложение имеет формат str.
сначала нам нужно все эти строки (подсписки) соединить в одну строку, где каждый символ(разделен) пробелом.

Поэтому сначала мы получим слова из каждого подсписка в формате списка

  `[sub_words = []

    for sublist in data_column:

        for word in sublist.split():
        
            sub_words.append(word)]`.

Теперь нам нужно список собрать в строку, для этого объединим все элементы этого списка

```
' '.join([word for lists in word_list)
```

Теперь мы имеем субтитры записанные в строковом формате, которые можно почистить от знаков препинаний и создать кортеж вместо списков.

Текст должен быть обработан от символов, иначе получается слишком много слов за счет того что Hello! и Hello считаются разными словами.



In [33]:
def extract_words(data_column):
    sub_words = []
    for sublist in data_column:
        for word in sublist.split():
            sub_words.append(word.lower())

    text = ' '.join(sub_words)
    pattern = r'[^\w\s\'\.]'
    text_cleaned = re.sub(pattern, '', text)

    return text_cleaned

In [34]:
data['cleaned_up_subs'] = data['subs'].apply(extract_words)
data['cleaned_up_subs'][0]

"  walkietalkie squawks   rick morgan i don't know if you're out there. i don't know if you can hear me. maybe you're listening right now. i hope so. i found others my family if you can believe it.  static  my wife and son they're alive. i wanted you to know that. there's something else you need to know. atlanta isn't what we thought. it's not what they promised. the city is do not enter the city. it belongs to the dead now. we're camped a few miles northwest up by a big abandoned rock quarry. you can see it on a map. i hope you come find us. but be careful. last night walkers came out of the woods. we lost people. watch yourself morgan. take care of your boy. i'll try you again tomorrow at dawn.  static  andrea. i'm so sorry. she's gone. you got to let us take her. we all cared about her and i promise we'll be as gentle as we can.  grunts   coughing  she still won't move lori won't even talk to us. she's been there all night. what do we do can't just leave amy like that. we need to de

У нас получился новый признак data['used_words'] который содержит все слова, использованные в каждом фильме.

### Обработка библиотекой NLTK

In [35]:
# Функция для токенизации, лемматизации и удаления стоп-слов
def preprocess_text(text):
    # Токенизация
    tokens = word_tokenize(text)

    # Лемматизация слов
    lemmatizer = WordNetLemmatizer()
    lemmatized_words = [lemmatizer.lemmatize(word) for word in tokens]

    # Удаление стоп-слов
    stop_words = set(stopwords.words('english'))
    filtered_words = [word for word in lemmatized_words if word.lower() not in stop_words]

    return filtered_words

In [36]:
## Применение обработки к столбцу субтитров
data['preprocessed_subs'] = data['cleaned_up_subs'].apply(preprocess_text)
data['preprocessed_subs'].head()

0    [walkietalkie, squawk, rick, morgan, n't, know...
1    [people, yelling, radio, chatter, hey, hey, .,...
2    [bird, chirping, nothing, ., 's, nothing, ., '...
3    [thunder, rumbling, merle, 's, right, ., heard...
4    [bird, chirping, bug, chittering, boy, mom, ri...
Name: preprocessed_subs, dtype: object

In [37]:
# Создание мешка слов для всех слов в датафрейме
word_counts = Counter()
for word_list in data['preprocessed_subs']:
    word_counts.update(word_list)
#word_counts

я создала второй мешок слов чтобы бегло сравнить результат работы, мне показалось что токенизация

```
word_tokenize()
```
показалась не очень эффективной.

попробовала применить


```
tokenize.RegexpTokenizer
```
и вообще получила неправильный результат. Возможно неправильный паттерн.


In [51]:
data.head()

subs  \
0  [- ( walkie-talkie squawks )\n- Rick: Morgan,,...   
1  [- ( people yelling )\n- ( radio chatter ), He...   
2  [( birds chirping ), - What?\n- Nothing., It's...   
3  [( thunder rumbling ), Merle:\nThat's right. Y...   
4  [- ( birds chirping )\n- ( bugs chittering ), ...   

                                               movie     id level _merge  \
0           the_walking_dead_s01e05_wildfire.english  116.0    a2   both   
1              the_walking_dead_s01e06_ts_19.english  117.0    a2   both   
2              the_walking_dead_s01e04_vatos.english  115.0    a2   both   
3  the_walking_dead_s01e03_tell_it_to_the_frogs.e...  114.0    a2   both   
4               the_walking_dead_s01e02_guts.english  113.0    a2   both   

                                     cleaned_up_subs  \
0    walkietalkie squawks   rick morgan i don't k...   
1    people yelling    radio chatter  hey hey. wh...   
2   birds chirping   what  nothing. it's not noth...   
3   thunder rumbling  merle that's right. you hea...   
4    birds chirping    bugs chittering  boy mom r...   

                                   preprocessed_subs  
0  [walkietalkie, squawk, rick, morgan, n't, know...  
1  [people, yelling, radio, chatter, hey, hey, .,...  
2  [bird, chirping, nothing, ., 's, nothing, ., '...  
3  [thunder, rumbling, merle, 's, right, ., heard...  
4  [bird, chirping, bug, chittering, boy, mom, ri...

In [38]:
word_counts_before = Counter()
word_counts_before.update(' '.join(data['cleaned_up_subs']).split())
#word_counts_before

In [55]:
data['preprocessed_subs'].apply(type).head()

0    <class 'list'>
1    <class 'list'>
2    <class 'list'>
3    <class 'list'>
4    <class 'list'>
Name: preprocessed_subs, dtype: object

In [57]:
data['preprocessed_subs'] = data['preprocessed_subs'].apply(str)
data['preprocessed_subs'].apply(type).head()

0    <class 'str'>
1    <class 'str'>
2    <class 'str'>
3    <class 'str'>
4    <class 'str'>
Name: preprocessed_subs, dtype: object

In [58]:
count = CountVectorizer()
bag = count.fit_transform(np.array(list(data['preprocessed_subs'])))

In [59]:
print (count.vocabulary_)

{'walkietalkie': 44438, 'squawk': 39041, 'rick': 35120, 'morgan': 28314, 'know': 24729, 're': 33918, 'hear': 18852, 'maybe': 27072, 'listening': 25760, 'right': 35168, 'hope': 19648, 'found': 16230, 'others': 30494, 'family': 14956, 'believe': 4153, 'static': 39283, 'wife': 45287, 'son': 38490, 'alive': 1842, 'wanted': 44509, 'something': 38451, 'else': 13700, 'need': 29005, 'atlanta': 3066, 'thought': 41519, 'promised': 33079, 'city': 7503, 'enter': 14049, 'belongs': 4197, 'dead': 11208, 'camped': 6316, 'mile': 27709, 'northwest': 29524, 'big': 4413, 'abandoned': 1017, 'rock': 35372, 'quarry': 33512, 'see': 36603, 'map': 26781, 'come': 9337, 'find': 15488, 'careful': 6501, 'last': 25058, 'night': 29271, 'walker': 44436, 'came': 6299, 'wood': 45633, 'lost': 26124, 'people': 31480, 'watch': 44626, 'take': 40534, 'care': 6488, 'boy': 5190, 'll': 25849, 'try': 42683, 'tomorrow': 42014, 'dawn': 11147, 'andrea': 2209, 'sorry': 38571, 'gone': 17566, 'got': 17664, 'let': 25412, 'cared': 6493,

In [61]:
print(type(bag))

<class 'scipy.sparse._csr.csr_matrix'>


In [60]:
print(bag.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [62]:
from sklearn.feature_extraction.text import TfidfTransformer




In [64]:
tfidf = TfidfTransformer(use_idf=True, norm='l2', smooth_idf=True)
tfidf_matrix = tfidf.fit_transform(bag)

In [ ]:
count = CountVectorizer()

# Преобразуем новый набор текстовых данных в мешок слов
new_bag = count.fit_transform(new_docs)

# Создаем объект TfidfTransformer
tfidf = TfidfTransformer(use_idf=True, norm='l2', smooth_idf=True)

# Применяем TF-IDF к новому мешку слов
tfidf_matrix = tfidf.fit_transform(new_bag)

Вывод:
Мы создали датасет, содержащий следующие колонки:
 - subs, id, movie, level, _merge, unique_words.

Все данные относятся к типу object, числовые признаки отсутствуют.

В ходе соединения

Предобработка включала в себя:
- замена пропущенных значений заглушкой
Сделали предварительную очистку субтитров:
-


# Подготовка модели

In [66]:
data.columns

Index(['subs', 'movie', 'id', 'level', '_merge', 'cleaned_up_subs',
       'preprocessed_subs'],
      dtype='object')

In [40]:
#Удалим лишние признаки
data = data.drop(['id', '_merge'], axis = 1)
data.head()

subs  \
0  [- ( walkie-talkie squawks )\n- Rick: Morgan,,...   
1  [- ( people yelling )\n- ( radio chatter ), He...   
2  [( birds chirping ), - What?\n- Nothing., It's...   
3  [( thunder rumbling ), Merle:\nThat's right. Y...   
4  [- ( birds chirping )\n- ( bugs chittering ), ...   

                                               movie level  \
0           the_walking_dead_s01e05_wildfire.english    a2   
1              the_walking_dead_s01e06_ts_19.english    a2   
2              the_walking_dead_s01e04_vatos.english    a2   
3  the_walking_dead_s01e03_tell_it_to_the_frogs.e...    a2   
4               the_walking_dead_s01e02_guts.english    a2   

                                     cleaned_up_subs  \
0    walkietalkie squawks   rick morgan i don't k...   
1    people yelling    radio chatter  hey hey. wh...   
2   birds chirping   what  nothing. it's not noth...   
3   thunder rumbling  merle that's right. you hea...   
4    birds chirping    bugs chittering  boy mom r...   

                                   preprocessed_subs  
0  [walkietalkie, squawk, rick, morgan, n't, know...  
1  [people, yelling, radio, chatter, hey, hey, .,...  
2  [bird, chirping, nothing, ., 's, nothing, ., '...  
3  [thunder, rumbling, merle, 's, right, ., heard...  
4  [bird, chirping, bug, chittering, boy, mom, ri...

In [67]:


# Ваш датасет с субтитрами
# data = ...

# Создаем мешок слов
count_vectorizer = CountVectorizer()
bag_of_words = count_vectorizer.fit_transform(data['preprocessed_subs'])

# Преобразуем мешок слов в TF-IDF векторы
tfidf_transformer = TfidfTransformer()
tfidf_matrix = tfidf_transformer.fit_transform(bag_of_words)

# Разделяем данные на обучающую и тестовую выборки
X_train, X_test, y_train, y_test = train_test_split(tfidf_matrix, data['level'], test_size=0.2, random_state=42)

# Обучаем модель логистической регрессии
model = LogisticRegression()
model.fit(X_train, y_train)

# Делаем предсказания на тестовой выборке
y_pred = model.predict(X_test)

# Оцениваем точность модели
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)


Accuracy: 0.6896551724137931
